error added to nemd_func process.Base stdout uses .std or .log (stderr combined) as extenstion lammps_driver.py errors the message in stderr process.Submodule raises stderr in addition if outfiles not found.

diff --git a/sh/nemd_func b/sh/nemd_func
--- a/sh/nemd_func
+++ b/sh/nemd_func
@@ -79,3 +79,9 @@ format_py()
   echo "Done!"
   return 0
 }
+
+# echo error message to std err and exit 1
+error() {
+  echo "Error: $1" >&2
+  exit 1
+  }
